version: '2'
services:
  worker:
    build: ../..
    image: bootlegger/transcode-server:latest
    command: nodemon --debug=5859
    ports:
      - "5859:5859"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
networks:
  default:
    external:
      name: serverapp_bootlegger-network